{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sentinel.fullname" . }}
  labels:
    app: {{ include "sentinel.name" . }}
    chart: {{ include "sentinel.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
spec:
  podSelector:
    matchLabels:
      app: {{ include "sentinel.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - {}
{{- end }}
