apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel.fullname" . }}
  labels:
    app: {{ include "sentinel.name" . }}
    chart: {{ include "sentinel.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "sentinel.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
