name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
          pip install coverage
      - name: Lint (ruff)
        run: |
          python -m ruff check .
          python -m ruff format --check .
      - name: Run tests
        run: |
          pytest -q --cov=sentinel --cov=services --cov-report=term-missing --cov-report=xml --cov-fail-under=90
      - name: Upload coverage xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}.xml
          path: coverage.xml
  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v5
      - name: Install hadolint
        run: |
          curl -sSfL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
          chmod +x /usr/local/bin/hadolint
      - name: Lint Dockerfile
        run: hadolint Dockerfile || echo "Hadolint warnings (non-blocking)"
      - name: Build image
        run: |
          docker build -t odin-webhook-sentinel:ci .
      - name: Trivy scan (non-blocking)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy image --severity HIGH,CRITICAL --no-progress --exit-code 0 odin-webhook-sentinel:ci || true
      - name: Smoke test container
        run: |
          docker run -d -p 8787:8787 --name sentinel odin-webhook-sentinel:ci
          sleep 5
          curl -sf http://127.0.0.1:8787/healthz | jq .ok | grep true
      - name: Cleanup
        if: always()
        run: |
          docker rm -f sentinel || truename: ci
