name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  id-token: write  # for keyless signing if enabled

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract version
        id: meta
        run: |
          TAG=${GITHUB_REF##*/}
          VERSION=${TAG#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Build wheels
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build
      - name: Build container
        run: |
          docker build -t ghcr.io/${{ github.repository }}/sentinel:${{ steps.meta.outputs.version }} .
          docker tag ghcr.io/${{ github.repository }}/sentinel:${{ steps.meta.outputs.version }} ghcr.io/${{ github.repository }}/sentinel:latest
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images
        run: |
          docker push ghcr.io/${{ github.repository }}/sentinel:${{ steps.meta.outputs.version }}
          docker push ghcr.io/${{ github.repository }}/sentinel:latest
      - name: Generate SBOM
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft ghcr.io/${{ github.repository }}/sentinel:${{ steps.meta.outputs.version }} -o spdx-json > SBOM.spdx.json
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: SBOM.spdx.json
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.meta.outputs.version }}
          name: v${{ steps.meta.outputs.version }}
          body: |
            See CHANGELOG.md for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Optional cosign keyless signing (commented):
      # - name: Cosign install
      #   uses: sigstore/cosign-installer@v3
      # - name: Cosign sign
      #   env:
      #     COSIGN_EXPERIMENTAL: 1
      #   run: |
      #     cosign sign ghcr.io/${{ github.repository }}/sentinel:${{ steps.meta.outputs.version }}
